**Titanic survial prediction**

In [98]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [99]:
data = pd.read_csv("titanic.csv")
data.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [100]:
data["Survived"].value_counts()

0    266
1    152
Name: Survived, dtype: int64

In [101]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [102]:
sexual_identity = pd.get_dummies(data['Sex'],drop_first=True)

In [103]:
sexual_identity

male
0       1
1       0
2       1
3       1
4       0
..    ...
413     1
414     0
415     1
416     1
417     1

[418 rows x 1 columns]

In [104]:
data.insert(5,'Sexual_identity',sexual_identity)

In [105]:
data.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex  Sexual_identity  \
0                              Kelly, Mr. James    male                1   
1              Wilkes, Mrs. James (Ellen Needs)  female                0   
2                     Myles, Mr. Thomas Francis    male                1   
3                              Wirz, Mr. Albert    male                1   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female                0   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [106]:
data.isna().sum()

PassengerId          0
Survived             0
Pclass               0
Name                 0
Sex                  0
Sexual_identity      0
Age                 86
SibSp                0
Parch                0
Ticket               0
Fare                 1
Cabin              327
Embarked             0
dtype: int64

In [107]:
average = data['Age'].mean()

In [108]:
average

30.272590361445783

In [109]:
data['Age'].fillna(average,inplace=True)

In [110]:
data['Fare'].fillna(data['Fare'].mean(),inplace=True)

In [111]:
data.isna().sum()

PassengerId          0
Survived             0
Pclass               0
Name                 0
Sex                  0
Sexual_identity      0
Age                  0
SibSp                0
Parch                0
Ticket               0
Fare                 0
Cabin              327
Embarked             0
dtype: int64

In [112]:
data[['PassengerId','Pclass','Age','SibSp','Parch','Fare','Sexual_identity']].values

array([[8.92000000e+02, 3.00000000e+00, 3.45000000e+01, ...,
        0.00000000e+00, 7.82920000e+00, 1.00000000e+00],
       [8.93000000e+02, 3.00000000e+00, 4.70000000e+01, ...,
        0.00000000e+00, 7.00000000e+00, 0.00000000e+00],
       [8.94000000e+02, 2.00000000e+00, 6.20000000e+01, ...,
        0.00000000e+00, 9.68750000e+00, 1.00000000e+00],
       ...,
       [1.30700000e+03, 3.00000000e+00, 3.85000000e+01, ...,
        0.00000000e+00, 7.25000000e+00, 1.00000000e+00],
       [1.30800000e+03, 3.00000000e+00, 3.02725904e+01, ...,
        0.00000000e+00, 8.05000000e+00, 1.00000000e+00],
       [1.30900000e+03, 3.00000000e+00, 3.02725904e+01, ...,
        1.00000000e+00, 2.23583000e+01, 1.00000000e+00]])

In [113]:
X=data[['PassengerId','Pclass','Sexual_identity','Age','SibSp','Parch','Fare']]
y=data['Survived']

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [115]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(292, 7) (126, 7) (292,) (126,)


In [116]:
from sklearn.linear_model import LogisticRegression

In [117]:
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [118]:
model.score(X_test,y_test)

1.0

In [119]:
model.predict([[1,1,0,38,0,0,7]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [120]:
model.predict([[1,3,1,30,0,0,8]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])